# name=input('enter your name')
# print('my name is',name)
# location=input('enter your location')
# email_id=input('enter your emailid')
# print('my location is',location)
# print('email id is',email_id)
# age=int(input('enter your age'))
# print('your age is',age)
# first_name=input('enter first name')
# salary=float(input('enter your salary'))
# pincode=int(input('enter your pincode'))
# address=input('enter your address')
# print('first name=',first_name)
# print('salary=',salary)
# print('pincode=',pincode)
# print('address=',address)
name=input('enter your name')
age=int(input('enter your age'))
print('my name is',name,'\nmy age is',age)
# age=10
# print('age is %d'%age)
# company=input('enter company name')
# location=input('enter location')
# print('%s is located in %s'%(company,location))
# employee_name=input('enter employee name')
# designation=input('enter your designation')
# phone=int(input('enter your phone number'))
# print('employee name=%s designation=%s phone=%d'%(employee_name,designation,phone))
